### ISSUE TITLE
Feedback for parsed files that have no issues

### ISSUE THREAD

**Issue by Robert-Frampton** [mthadley/metal-soy-critic#4]
Hey guys, awesome idea for a tool!

The first time I ran it on a file, it didn't find any issues so there was no output. This made me think it was potentially a bug, and I wasn't sure if it actually read the file or not.

It might be nice to have output that lists all files that pass your checks, similar to test output which lists both the tests that pass and the ones that fail. Maybe something like...

```bash
The following 1 file(s) passed all checks:

File - src/SomeFile.soy
```

**Comment by mthadley** [comment]
@Robert-Frampton Sounds like a great idea! There are still a lot of improvements to be made in the usability.

**Comment by ethib137** [comment]
I like this idea, but it would be great to also include the option `-q` or `--quiet` that would not print out anything for files with no errors.

**Comment by ethib137** [comment]
Fixed by: https://github.com/mthadley/metal-soy-critic/pull/6
