### ISSUE TITLE
Missing import imcompatible with unused variable

### ISSUE THREAD

**Issue by jbalsas** [mthadley/metal-soy-critic#8]
We are currently looking for imports in a componente when a template is used, so if you're using `{call Dropdown.render}` we're looking (I guess ) for an `import Dropdown from...` statement.

If not found, we have get the following message: 

```sh
File - src/main/resources/META-INF/resources/components/configurabledropdown/ConfigurableDropdown.soy

     It looks like the following component calls are missing an import:
     
     Dropdown
```

This is incompatible with `estlint::unused-var` rule, so we usually have 

```javascript
import metal-dropdown // avoid declaring Dropdown when not used
```

**Comment by mthadley** [comment]
@jbalsas It's not very sophisticated. It's just checking for an `import` statement that contains the namespace in it's path. So something like `import "./Dropdown.soy"` should be fine.

I think it's case-sensitive, so that is why it's failing. I'm guessing if you change it to `{call dropdown.render /}` is probably doesn't fail.

**Comment by jbalsas** [comment]
Yeah, that's what I figured it should be doing... since we can't change the namespace or the import... what do you think would be the quickest _fix_? Just make the check case-insensitive? 😂

**Comment by mthadley** [comment]
Yea, for the moment I think it's a reasonable improvement. I'll update it soon.

**Comment by jbalsas** [comment]
Hey @mthadley, I wanted to apply this to https://github.com/metal/metal-clay-components where we have `import 'clay-icon';` and `{call ClayIcon.render}`.

Do we have a `.soycriticrc` or maybe `soycritic.config.js` where we could maybe add config option like `jsImportToSoyCallRegex` so we could fix this in a general/configurable way?

What do you think?

**Comment by mthadley** [comment]
@jbalsas We don't, however I think it's a great idea.
