### ISSUE TITLE
Allow for a metal-soy-critic config file.

### ISSUE THREAD

**Issue by mthadley** [mthadley/metal-soy-critic#9]
We have a few cases where configuration makes sense for `metal-soy-critic`. One use case is allowing for a custom regex when determining the matching import path for a component having it's `render` template called.

Let's go with a config file like `.soycriticrc` or` soycritic.config.js`. The CLI can recursively look in parent directories for this file, and read it's configuration when one is found.

/cc @jbalsas

**Comment by mthadley** [comment]
I have some work done on this, I'll try to get something out soon.

**Comment by jbalsas** [comment]
Awesome, @mthadley! No need to rush it ☺️

**Comment by mthadley** [comment]
@jbalsas See `2.2.0`, and the configuration section in the README. Let me know if that solves your use case.

**Comment by jbalsas** [comment]
It seems to fix it, indeed! ☺️
